// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd-dDONDJgEf6WbjtCoIi4bWO2M8OHsPs',
    appId: '1:868512172399:web:09d4b6a72335968e63c09a',
    messagingSenderId: '868512172399',
    projectId: 'expense-tracker-mobile-a-eab13',
    authDomain: 'expense-tracker-mobile-a-eab13.firebaseapp.com',
    storageBucket: 'expense-tracker-mobile-a-eab13.firebasestorage.app',
    measurementId: 'G-XJV094ZYE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUpt3FwSo2NIaaCmkAot_oj--31MjZ0Cg',
    appId: '1:868512172399:android:7dc30c035c42616163c09a',
    messagingSenderId: '868512172399',
    projectId: 'expense-tracker-mobile-a-eab13',
    storageBucket: 'expense-tracker-mobile-a-eab13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0lmkkjEdMFY1ynMt9X-0ya9QzEjtpqho',
    appId: '1:868512172399:ios:6118324f4a1b328763c09a',
    messagingSenderId: '868512172399',
    projectId: 'expense-tracker-mobile-a-eab13',
    storageBucket: 'expense-tracker-mobile-a-eab13.firebasestorage.app',
    androidClientId: '868512172399-uj4a3damvhmo2j0pchcbbjjci2eoacgg.apps.googleusercontent.com',
    iosClientId: '868512172399-vq61nta00omo78kng28919udb860reo0.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTrackerMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0lmkkjEdMFY1ynMt9X-0ya9QzEjtpqho',
    appId: '1:868512172399:ios:6118324f4a1b328763c09a',
    messagingSenderId: '868512172399',
    projectId: 'expense-tracker-mobile-a-eab13',
    storageBucket: 'expense-tracker-mobile-a-eab13.firebasestorage.app',
    androidClientId: '868512172399-uj4a3damvhmo2j0pchcbbjjci2eoacgg.apps.googleusercontent.com',
    iosClientId: '868512172399-vq61nta00omo78kng28919udb860reo0.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTrackerMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd-dDONDJgEf6WbjtCoIi4bWO2M8OHsPs',
    appId: '1:868512172399:web:87e55527e782330e63c09a',
    messagingSenderId: '868512172399',
    projectId: 'expense-tracker-mobile-a-eab13',
    authDomain: 'expense-tracker-mobile-a-eab13.firebaseapp.com',
    storageBucket: 'expense-tracker-mobile-a-eab13.firebasestorage.app',
    measurementId: 'G-DV5LQR8Z64',
  );

}