import 'package:flutter/widgets.dart';

class AppLocalizations {
  const AppLocalizations(this.locale);

  final Locale locale;

  static const delegate = _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        const AppLocalizations(Locale('en'));
  }

  String t(String key) {
    final language = locale.languageCode;
    return _translations[language]?[key] ?? _translations['en']![key] ?? key;
  }

  String expenseCount(int count) => t(
    count == 1 ? 'expense_one' : 'expense_many',
  ).replaceFirst('{count}', '$count');

  String removeExpense(String title) =>
      t('remove_expense').replaceFirst('{title}', title);

  String categoryLabel(String category) => t(category);

  static const _translations = <String, Map<String, String>>{
    'en': {
      'welcome': 'Welcome to Ledgerly',
      'sign_in_subtitle': 'Sign in to access your expense history.',
      'register_subtitle': 'Create an account to keep your expenses in sync.',
      'email': 'Email',
      'password': 'Password',
      'confirm_password': 'Confirm password',
      'new_password': 'New password',
      'sign_in': 'Sign in',
      'create_account': 'Create account',
      'continue_google': 'Continue with Google',
      'or': 'OR',
      'new_here': 'New here? Create an account',
      'already_account': 'Already have an account? Sign in',
      'valid_email': 'Enter a valid email',
      'min_password': 'Use at least 6 characters',
      'passwords_match': 'Passwords do not match',
      'account_settings': 'Account & settings',
      'signed_in_as': 'Signed in as',
      'currency': 'Currency',
      'language': 'Language',
      'change_password': 'Change password',
      'reset_history': 'Reset expense history',
      'sign_out': 'Sign out',
      'change_password_title': 'Change password',
      'update_password': 'Update password',
      'cancel': 'Cancel',
      'password_updated': 'Password updated.',
      'google_no_password': 'Google accounts do not use an app password.',
      'password_failed': 'Could not update password. Sign in again and retry.',
      'delete_history_title': 'Reset expense history?',
      'delete_history_body':
          'This permanently deletes every expense in your account. This action cannot be undone.',
      'delete_everything': 'Delete everything',
      'reset_failed': 'Could not reset expense history.',
      'sign_out_failed': 'Could not sign out.',
      'overview': 'overview',
      'total_spent': 'Total spent',
      'ready_first': 'Ready for your first expense',
      'recent_expenses': 'Recent expenses',
      'add_expense': 'Add expense',
      'no_expenses': 'No expenses yet',
      'no_matching': 'No matching expenses',
      'search_expenses': 'Search expenses',
      'search_hint': 'Title, note, or category',
      'expense_one': '{count} expense this month',
      'expense_many': '{count} expenses this month',
      'remove_expense': 'Remove "{title}" from your history?',
      'delete_expense': 'Delete expense?',
      'delete': 'Delete',
      'edit': 'Edit',
      'all': 'All',
      'date': 'Date',
      'clear_filters': 'Clear filters',
      'expense_actions': 'Expense actions',
      'could_not_load': 'Could not load expenses',
      'try_again': 'Try again',
      'new_expense': 'New expense',
      'edit_expense': 'Edit expense',
      'title': 'Title',
      'title_hint': 'e.g. Weekly groceries',
      'amount': 'Amount',
      'amount_hint': '0.00',
      'category': 'Category',
      'note_optional': 'Note (optional)',
      'note_hint': 'Add a little context',
      'close': 'Close',
      'save_changes': 'Save changes',
      'system_theme': 'Use system theme',
      'light_theme': 'Light theme',
      'dark_theme': 'Dark theme',
      'expense_deleted': 'Expense deleted',
      'undo': 'Undo',
      'undo_failed': 'Could not restore expense.',
      'see_more': 'See more',
      'food': 'Food',
      'transport': 'Transport',
      'shopping': 'Shopping',
      'bills': 'Bills',
      'health': 'Health',
      'entertainment': 'Entertainment',
      'other': 'Other',
    },
    'si': {
      'welcome': 'Ledgerly වෙත සාදරයෙන් පිළිගනිමු',
      'sign_in_subtitle': 'ඔබේ වියදම් ඉතිහාසයට ප්‍රවේශ වීමට පුරනය වන්න.',
      'register_subtitle': 'ඔබේ වියදම් සමමුහුර්ත කිරීමට ගිණුමක් සාදන්න.',
      'email': 'විද්‍යුත් තැපෑල',
      'password': 'මුරපදය',
      'confirm_password': 'මුරපදය තහවුරු කරන්න',
      'new_password': 'නව මුරපදය',
      'sign_in': 'පුරනය වන්න',
      'create_account': 'ගිණුම සාදන්න',
      'continue_google': 'Google සමඟ ඉදිරියට යන්න',
      'or': 'හෝ',
      'new_here': 'අලුත්ද? ගිණුමක් සාදන්න',
      'already_account': 'දැනටමත් ගිණුමක් තිබේද? පුරනය වන්න',
      'valid_email': 'වලංගු විද්‍යුත් තැපෑලක් ඇතුළත් කරන්න',
      'min_password': 'අවම වශයෙන් අක්ෂර 6ක් භාවිතා කරන්න',
      'passwords_match': 'මුරපද නොගැලපේ',
      'account_settings': 'ගිණුම සහ සැකසුම්',
      'signed_in_as': 'පුරනය වී ඇත්තේ',
      'currency': 'මුදල් ඒකකය',
      'language': 'භාෂාව',
      'change_password': 'මුරපදය වෙනස් කරන්න',
      'reset_history': 'වියදම් ඉතිහාසය යළි සකසන්න',
      'sign_out': 'ඉවත් වන්න',
      'change_password_title': 'මුරපදය වෙනස් කරන්න',
      'update_password': 'මුරපදය යාවත්කාලීන කරන්න',
      'cancel': 'අවලංගු කරන්න',
      'delete_history_title': 'වියදම් ඉතිහාසය යළි සකසන්නද?',
      'delete_everything': 'සියල්ල මකන්න',
      'overview': 'සාරාංශය',
      'total_spent': 'මුළු වියදම',
      'recent_expenses': 'මෑත වියදම්',
      'add_expense': 'වියදම එක් කරන්න',
      'no_expenses': 'තවම වියදම් නැත',
      'no_matching': 'ගැළපෙන වියදම් නැත',
      'search_expenses': 'වියදම් සොයන්න',
      'search_hint': 'මාතෘකාව, සටහන හෝ වර්ගය',
      'expense_one': 'මෙම මාසයේ වියදම් {count}ක්',
      'expense_many': 'මෙම මාසයේ වියදම් {count}ක්',
      'remove_expense': '"{title}" ඉතිහාසයෙන් ඉවත් කරන්නද?',
      'delete_expense': 'වියදම මකන්නද?',
      'delete': 'මකන්න',
      'edit': 'සංස්කරණය',
      'all': 'සියල්ල',
      'date': 'දිනය',
      'clear_filters': 'පෙරහන් මකන්න',
      'expense_actions': 'වියදම් ක්‍රියා',
      'could_not_load': 'වියදම් පූරණය කළ නොහැක',
      'try_again': 'නැවත උත්සාහ කරන්න',
      'new_expense': 'නව වියදම',
      'edit_expense': 'වියදම සංස්කරණය',
      'title': 'මාතෘකාව',
      'title_hint': 'උදා: සතිපතා සාප්පු',
      'amount': 'මුදල',
      'amount_hint': '0.00',
      'category': 'වර්ගය',
      'note_optional': 'සටහන (විකල්ප)',
      'note_hint': 'විස්තරයක් එක් කරන්න',
      'close': 'වසන්න',
      'save_changes': 'වෙනස්කම් සුරකින්න',
      'system_theme': 'පද්ධති තේමාව භාවිතා කරන්න',
      'light_theme': 'ආලෝක තේමාව',
      'dark_theme': 'අඳුරු තේමාව',
      'expense_deleted': 'වියදම මකා දමන ලදී',
      'undo': 'ආපසු කරන්න',
      'undo_failed': 'වියදම ප්‍රතිසාධනය කළ නොහැක.',
      'see_more': 'තවත් බලන්න',
      'food': 'ආහාර',
      'transport': 'ප්‍රවාහනය',
      'shopping': 'සාප්පු සවාරි',
      'bills': 'බිල්පත්',
      'health': 'සෞඛ්‍යය',
      'entertainment': 'විනෝදාස්වාදය',
      'other': 'වෙනත්',
    },
    'ta': {
      'welcome': 'Ledgerly க்கு வரவேற்கிறோம்',
      'sign_in_subtitle': 'உங்கள் செலவு வரலாற்றை அணுக உள்நுழையவும்.',
      'register_subtitle': 'செலவுகளை ஒத்திசைக்க கணக்கை உருவாக்கவும்.',
      'email': 'மின்னஞ்சல்',
      'password': 'கடவுச்சொல்',
      'confirm_password': 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
      'new_password': 'புதிய கடவுச்சொல்',
      'sign_in': 'உள்நுழை',
      'create_account': 'கணக்கை உருவாக்கு',
      'continue_google': 'Google மூலம் தொடரவும்',
      'or': 'அல்லது',
      'new_here': 'புதியவரா? கணக்கை உருவாக்கவும்',
      'already_account': 'ஏற்கனவே கணக்கு உள்ளதா? உள்நுழையவும்',
      'valid_email': 'சரியான மின்னஞ்சலை உள்ளிடவும்',
      'min_password': 'குறைந்தது 6 எழுத்துகளைப் பயன்படுத்தவும்',
      'passwords_match': 'கடவுச்சொற்கள் பொருந்தவில்லை',
      'account_settings': 'கணக்கு மற்றும் அமைப்புகள்',
      'signed_in_as': 'உள்நுழைந்தவர்',
      'currency': 'நாணயம்',
      'language': 'மொழி',
      'change_password': 'கடவுச்சொல்லை மாற்று',
      'reset_history': 'செலவு வரலாற்றை மீட்டமை',
      'sign_out': 'வெளியேறு',
      'change_password_title': 'கடவுச்சொல்லை மாற்று',
      'update_password': 'கடவுச்சொல்லைப் புதுப்பி',
      'cancel': 'ரத்து செய்',
      'delete_history_title': 'செலவு வரலாற்றை மீட்டமைக்கவா?',
      'delete_everything': 'அனைத்தையும் நீக்கு',
      'overview': 'கண்ணோட்டம்',
      'total_spent': 'மொத்த செலவு',
      'recent_expenses': 'சமீபத்திய செலவுகள்',
      'add_expense': 'செலவைச் சேர்',
      'no_expenses': 'செலவுகள் இல்லை',
      'no_matching': 'பொருந்தும் செலவுகள் இல்லை',
      'search_expenses': 'செலவுகளைத் தேடு',
      'search_hint': 'தலைப்பு, குறிப்பு அல்லது வகை',
      'expense_one': 'இந்த மாதம் {count} செலவு',
      'expense_many': 'இந்த மாதம் {count} செலவுகள்',
      'remove_expense': '"{title}" வரலாற்றிலிருந்து அகற்றவா?',
      'delete_expense': 'செலவை நீக்கவா?',
      'delete': 'நீக்கு',
      'edit': 'திருத்து',
      'all': 'அனைத்தும்',
      'date': 'தேதி',
      'clear_filters': 'வடிப்பான்களை அழி',
      'expense_actions': 'செலவு செயல்கள்',
      'could_not_load': 'செலவுகளை ஏற்ற முடியவில்லை',
      'try_again': 'மீண்டும் முயற்சிக்கவும்',
      'new_expense': 'புதிய செலவு',
      'edit_expense': 'செலவைத் திருத்து',
      'title': 'தலைப்பு',
      'title_hint': 'எ.கா. வாராந்திர மளிகை',
      'amount': 'தொகை',
      'amount_hint': '0.00',
      'category': 'வகை',
      'note_optional': 'குறிப்பு (விருப்பம்)',
      'note_hint': 'சிறு விவரத்தைச் சேர்க்கவும்',
      'close': 'மூடு',
      'save_changes': 'மாற்றங்களைச் சேமி',
      'system_theme': 'கணினி தீமை பயன்படுத்து',
      'light_theme': 'ஒளி தீமை',
      'dark_theme': 'இருண்ட தீமை',
      'expense_deleted': 'செலவு நீக்கப்பட்டது',
      'undo': 'மீட்டமை',
      'undo_failed': 'செலவை மீட்டெடுக்க முடியவில்லை.',
      'see_more': 'மேலும் பார்க்க',
      'food': 'உணவு',
      'transport': 'போக்குவரத்து',
      'shopping': 'ஷாப்பிங்',
      'bills': 'பில்கள்',
      'health': 'ஆரோக்கியம்',
      'entertainment': 'பொழுதுபோக்கு',
      'other': 'மற்றவை',
    },
  };
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['en', 'si', 'ta'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
